name: CI for Flask App

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.12, 3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: |
          flake8 .

      - name: Run unit tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t flask-ci-cd-demo .

      - name: Login to Docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag ci-cd-demo-flask ${{secrets.DOCKER_USERNAME}}/ci-cd-demo-flask:latest

      - name: Push image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-demo-flask:latest
